name: TEST
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
jobs:
  Build:
    uses: raghudevopsb84/learn-github-actions/.github/workflows/test1.yml@main
    with:
      appType: 'nodejs'
      appName: 'cart'
    secrets:
      vault_token: ${{ secrets.vault_token }}

